name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 2.0.29
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.9.0 <3.0.0"

#dependencies:

dev_dependencies:
  test: ^1.14.3
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
